export const projects = [
  {
    title: 'React Portfolio',
    description: "Using React I have created an amazing and beautiful portfolio. This portfolio will tell you about my skills and hobbies.",
      image: '/images/11.jpg',
      tags: ['Tailwind Css','React'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/9.jpg',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/9.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/9.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
    
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/9.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
    
  },
  {
    title: 'UPCOMING PROJECT',
    description: "This is an upcoming project",
    image: '/images/9.jpg',
    tags: ['AWS', 'Amazon', 'Cloud'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'CERTIFICATION ',
    description: "Fundamentals of Data Analytics ",
    image: '/images/5.jpg',
    tags: ['LEAPS', 'DATA',],
    id: 4,
  },
  {
    title: 'CERTIFICATION ',
    description: "Fundamentals of Data Analytics",
    image: '/images/6.jpg',
    tags: ['NASSCOM', 'DATA'],
    id: 5,
  },
  {
    title: 'CERTIFICATION',
    description: "DSA zero to Hero By Up degree",
    image: '/images/7.jpg',
    tags: ['DSA', 'Udemy', 'c++'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
  {
    title: 'CERTIFICATION',
    description: "AWS certified cloud practitioner by Stephane Maarek",
    image: '/images/8.jpg',
    tags: ['AWS', 'Udemy', 'Cloud'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
  {
    title: 'UPCOMING AWS CERTIFICATION',
    description: "AWS certified cloud practitioner (Expected date : 1st week of june)",
    image: '/images/10.jpg',
    tags: ['AWS', 'Amazon', 'Cloud'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Completed School education', },
  { year: 2020, text: 'Joined Vellore instute of technology', },
  
];